AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple Task Manager API

Globals:
  Function:
    Runtime: python3.7
    Timeout: 29
    Environment:
      Variables:
        TABLE_NAME: data-table

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: simple-task-manager-api
      StageName: prd
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'POST,GET,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
#      Domain:
#        DomainName: www.my-domain.com
#        CertificateArn: my-valid-cert-arn
#        EndpointConfiguration: EDGE

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /hello
            Method: get

  InlineCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        import json
        def lambda_handler(event, context):
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "message": "OK",
                }),
            }
      Handler: index.lambda_handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /inline-code
            Method: get
